jobs:
- job: Build
  steps:
  - script: |
      npm install
    displayName: 'Install npm'

  - script: |
      cd frontend
      npm install
    displayName: 'Install frontend npm'

  - script: |
      cd backend
      npm install
    displayName: 'Install backend npm'

  - script: | 
      npm start > server.log 2>&1 &
      echo "Waiting for server to start..."
      sleep 30 # Increase wait time if necessary

      # Check if server is up
      curl --silent --fail http://localhost:3001 || (echo "Server failed to start" && tail -n 20 server.log && exit 1)
    displayName: 'Start server'
  
  - script: |
      cd frontend
      npx cypress run --config-file cypress.config.js
    displayName: 'Run Cypress tests'

