jobs:
- job: Build
  steps:
  - script: |
      npm install
      npm start &
      echo "Waiting for server to start..."
      sleep 20
    displayName: 'Start server'
  
  - script: |
      cd frontend
      npx cypress run
    displayName: 'Run Cypress tests'

