trigger:
  branches:
    include:
      - main  # Sostituisci con il branch che vuoi monitorare

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.13'  # Specifica la versione di Node.js che ti serve

  - script: |
      cd frontend
      npm install
    displayName: 'Installare le dipendenze del frontend'

  - script: |
      cd backend
      npm install  # Installa le dipendenze per il backend
    displayName: 'Installa le dipendenze del backend'

  - script: |
      npm start &
      displayName: 'Avvia il server backend'

  - script: |
      npx wait-on http://localhost:3001  # Attendi che il frontend sia pronto
      npx wait-on http://localhost:4000  # Attendi che il backend sia pronto
    displayName: 'Attendi che i server siano pronti'

  - script: |
      cd frontend
      npx cypress install
    displayName: 'Installare Cypress'

  - script: |
      cd frontend
      ls -la  # Debug: elenca i file nella directory corrente
    displayName: 'Debug: Lista dei file'

  - script: |
      cd frontend
      npx cypress run --config-file cypress.config.js 
    displayName: 'Esegui i test di Cypress'

