trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - script: echo Hello, Azure DevOps!
  - script: echo Building your project...
  - script: echo Add your build steps here


