variables:
  PORT: '3001'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@0
  inputs:
    versionSpec: '18.13.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    cd frontend
    npm install
  displayName: 'Install dependencies'

- script: |
    cd backend
    npm install
  displayName: 'Install dependencies'

- script: |
    npm start &
  displayName: 'Start the application'

- script: |
    cd frontend
    npx cypress run --reporter mocha-junit-reporter

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'frontend/cypress/results/test-results.xml'
    testRunTitle: 'Cypress Test Results'


