trigger:
  branches:
    include:
      - main  # Sostituisci con il branch che vuoi monitorare

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.13'  # Specifica la versione di Node.js che ti serve

  - script: |
      npm install  # Installa le dipendenze nella cartella principale
    displayName: 'Installa le dipendenze'

  - script: |
      npm start --prefix frontend &  # Avvia il frontend in background
      npm start --prefix backend &  # Avvia il backend in background
    displayName: 'Avvia i server frontend e backend'

  - script: |
      npx wait-on http://localhost:3001  # Attendi che il frontend sia pronto
      npx wait-on http://localhost:4000  # Attendi che il backend sia pronto
    displayName: 'Attendi che i server siano pronti'

  - script: |
      npx cypress run --config-file frontend/cypress.config.js  # Esegui i test di Cypress
    displayName: 'Esegui i test di Cypress'
