jobs:
- job: Build
  steps:
  - script: |
      npm install
  - script: |
      cd frontend
      npm install
    displayName: 'Install frontend npm'

  - script: |
      cd backend
      npm install
    displayName: 'Install backend npm'

  - script: | 
      npm start &
      echo "Waiting for server to start..."
      sleep 20
    displayName: 'Start server'
  
  - script: |
      cd frontend
      npx cypress run
    displayName: 'Run Cypress tests'

