trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '18.13.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    cd frontend
    npm install
  displayName: 'Install dependencies'

- script: |
    cd backend
    npm install
  displayName: 'Install dependencies'

- script: |
    npm start
  displayName: 'Start the application'


