variables:
  PORT: '3001'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@0
  inputs:
    versionSpec: '18.13.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    cd frontend
    npm install
  displayName: 'Install dependencies'

- script: |
    cd backend
    npm install
  displayName: 'Install dependencies'

- script: |
    npm start &
  displayName: 'Start the application'

- script: |
    set -x
    cd frontend
    npx cypress run --reporter mocha-junit-reporter --reporter-options mochaFile=results/test-results.xml || true
  displayName: 'Cypress run test'
    

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    mergeTestResults: true
    testRunTitle: 'Cypress Test Results'

- script: |
    ls -la frontend/cypress/results/
  displayName: 'Check Cypress Results Directory'




