trigger:
  branches:
    include:
      - main  # Sostituisci con il branch che vuoi monitorare

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.13'  # Specifica la versione di Node.js che ti serve

  - script: |
      npm install
    displayName: 'Installare le dipendenze'

  - script: |
      npx cypress install
    displayName: 'Installare Cypress'

  - script: |
      npx cypress run --config-file frontend/cypress.config.json 
    displayName: 'Esegui i test di Cypress'

